name: Check linting health

on: [push]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Install packages
      run: yarn
    
    - name: Check linting
      run: yarn lint